select name, country_id, HIRE_DATE,
DENSE_RANK from
(select e.first_name||e.last_name name, e.HIRE_DATE, country_id ,
DENSE_RANK() OVER (PARTITION BY l.country_id ORDER BY e.HIRE_DATE) DENSE_RANK 
from employees e join departments d on e.DEPARTMENT_ID=d.DEPARTMENT_ID
join locations l on d.location_id = l.LOCATION_ID) a
where a.DENSE_RANK = 1 ; 
-----------------------------------------------
select * from employees;
-----------------------------------------------COUNT(*) OVER (PARTITION BY deptno)
SELECT JOB_ID, 
COUNT(*) OVER (PARTITION BY 
DEPARTMENT_ID) DEPARTMENT_ID
FROM employees
---------------------------------------------ROW_NUMBER, RANK and DENSE_RANK,LEAD,LAG
SELECT EMPLOYEE_ID, DEPARTMENT_ID, HIRE_DATE,SALARY,
ROW_NUMBER( ) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC NULLS LAST) ROW_NUMBER,
RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC NULLS LAST) RANK,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC NULLS LAST) DENSE_RANK,
COUNT(*) OVER (PARTITION BY  DEPARTMENT_ID) "COUNT(*)_DEPARTMENT_ID",
LEAD(SALARY, 1, 0) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC NULLS LAST) NEXT_LOWER_SAL,
LAG(SALARY, 1, 0) OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC NULLS LAST) PREV_HIGHER_SAL
FROM employees
--where 
--DEPARTMENT_ID = 50 
ORDER BY DEPARTMENT_ID;

---------------------------------------------ROW_NUMBER, RANK and DENSE_RANK,LEAD,LAG
SELECT EMPLOYEE_ID, DEPARTMENT_ID, HIRE_DATE,SALARY,

LEAD(SALARY, 1, 0) OVER (PARTITION BY department_id ORDER BY HIRE_DATE DESC NULLS LAST) NEXT_LOWER_SAL

FROM employees
--where 
--DEPARTMENT_ID = 50 
ORDER BY DEPARTMENT_ID,HIRE_DATE;
---------------------------------------